name: 'Build and Deploy'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          npm install

      - name: Build Code
        run: npm run build

      - name: Get ready for Deployment
        run: |
          npm run package
          npm run patch --force
          git add dist
          git commit -a -m "Automated Update"
          git push origin releases/v1


