name: Move Major Release Tag

on:
    release:
      types:
        - published
        - edited

jobs:
  movetag:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Run latest-tag
          uses: EndBug/latest-tag@latest
          with:
            description: latest  

        - name: Update latest     
          uses: Actions-R-Us/actions-tagger@latest
          with:
           publish_latest_tag: true

       
           
            # # Force-update a branch instead of using a tag.
            # # Default: false
            # force-branch: true
    # - uses: actions/checkout@v3
    #   with:
    #     fetch-depth: 0 

    # - name: Get major version num and update tag
    #   run: |
    #     VERSION=${GITHUB_REF#refs/tags/}
    #     MAJOR=${VERSION%%.*}
    #     git config --global user.name 'Automata'
    #     git config --global user.email 'RockiRider@users.noreply.github.com'
    #     git tag -fa ${MAJOR} -m "Update major version tag"
    #     git push origin ${MAJOR} --force
    